package uom.research.thalassemia.ui;

import java.awt.Frame;
import javax.swing.ImageIcon;
import uom.research.thalassemia.util.ResizeImage;

/**
 *
 * @author anupama
 */
public final class About extends javax.swing.JDialog {

    /**
     * Frame width.
     */
    private static final int FRAME_WIDTH = 410;
    /**
     * Frame height.
     */
    private static final int FRAME_HEIGHT = 520;

    /**
     * Creates new form About.
     *
     * @param parent parent frame
     * @param modal is modal or not
     */
    public About(final Frame parent, final boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(FRAME_WIDTH, FRAME_HEIGHT);
        jLabel2.setIcon(new ImageIcon("/resources/about.jpg"));
        this.setIconImage(ResizeImage.resizeImage("/resources/icon.jpg")
                .getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 180));

        jLabel1.setText("<html> \t<head> \t\t<style> \t\ttable { \t\t\tborder-collapse: collapse; \t\t\twidth:100%; \t\t} \t\ttable, th, td { \t\t\tborder: 1px solid black; \t\t} \t\t</style> \t</head> \t\t<body> \t\t<center> \t\t\t<table> \t\t\t\t<tr> \t\t\t\t\t<th>UOM ID</th><th>Name</th><th>Contact #</th> \t\t\t\t</tr> \t\t\t\t<tr> \t\t\t\t\t<td>115015F</td><td>Yasanthi Anupama</td><td>0713212637</td> \t\t\t\t</tr> \t\t\t\t<tr> \t\t\t\t\t<td>IT11165644</td><td>Hansa Amarasekara</td><td>0712004212</td> \t\t\t\t</tr> \t\t\t\t<tr> \t\t\t\t\t<td>anyno</td><td>somebody</td><td>0772004212</td> \t\t\t\t</tr> \t\t\t\t<tr> \t\t\t\t\t<td>thisno</td><td>Someone</td><td>0762004212</td> \t\t\t\t</tr> \t\t\t</table> \t\t</body> \t</center> </html>");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 280, 140));

        jLabel3.setText("<html> \t<head> \t</head> \t<body> \t\t<p> \t\t\t<font style=\"color:#ff0000\">Thalassemia</font> is a blood disorder involving less than normal amounts of an oxygen-carrying protein.  \t\t</p> \t\t<p>Doctors diagnose thalassemias using blood tests, including a complete blood count (CBC) and special hemoglobin tests. <ul>     <li>A CBC measures the amount of hemoglobin and the different kinds of blood cells, such as red blood cells, in a sample of blood. ...</li>     <li>Hemoglobin tests measure the types of hemoglobin in a blood sample.</li> </ul> \t\t</p> \t</body> </html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 380, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
