/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uom.research.thalassemia.ui;

import javax.swing.table.DefaultTableModel;
import org.opencv.core.Mat;

/**
 *
 * @author anupama
 */
public final class CircleData extends javax.swing.JFrame {

    /**
     * Circles set.
     */
    private final Mat circles;

    /**
     * pi constant.
     */
    private final double fi = 22.0 / 7.0;

    /**
     * Creates new form CircleData.
     *
     *
     * @param circleSet circles
     */
    public CircleData(final Mat circleSet) {
        initComponents();
        this.circles = circleSet;
        setLocationRelativeTo(null);
        fillTable();
    }

    /**
     * fill table.
     */
    private void fillTable() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        double[] circle;
        int index;
        double x, y, r, area, perimeter;
        for (int a = 0; a < circles.cols(); a++) {
            index = a + 1;
            circle = circles.get(0, a);
            x = circle[0];
            y = circle[1];
            r = Math.round(circle[2]);
            area = fi * r * r;
            perimeter = 2 * fi * r;
            Object[] ob = {index, x, y, r, area, perimeter};
            dtm.addRow(ob);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Circle Data");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "x", "y", "r", "perimeter", "area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
