/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uom.research.thalassemia.ui;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import uom.research.thalassemia.object.User;
import uom.research.thalassemia.util.BarChartCreator;
import uom.research.thalassemia.util.FillData;
import uom.research.thalassemia.util.Message;
import uom.research.thalassemia.util.ObjectDockLoader;
import uom.research.thalassemia.util.PieChartCreator;

/**
 *
 * @author hansa
 */
public class HomeMain extends javax.swing.JFrame {

    /**
     * simple date time formatter. yyyy-MM-dd HH:mm:ss
     */
    private static final SimpleDateFormat DATE_TIME_FORMAT
            = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    /**
     * DateTime keeper.
     */
    private Date date;

    /**
     * One Second In MiliSeconds.
     */
    private static final int ONE_S_IN_MS = 1000;

    /**
     * logged in user.
     */
    private final User user;

    /**
     * Creates new form HomeMain.
     *
     * @param pUser user
     */
    public HomeMain(final User pUser) {
        initComponents();
        setSize(900, 700);
        user = pUser;
        setLocationRelativeTo(null);
        System.out.println(this.getWidth());
        lblBanner.setSize(this.getWidth(), 50);
        ObjectDockLoader objectDockLoader = new ObjectDockLoader(DocBarPane,
                HomeMain.this);
        objectDockLoader.toString();
        FillData.setIconForJFrame(HomeMain.this);
        setClock();
    }

    /**
     * run clock.
     */
    private void setClock() {
        Timer t = new Timer(ONE_S_IN_MS, (ActionEvent evt) -> {
            date = new Date();
            lblDateAndTime.setText("\t\t" + DATE_TIME_FORMAT.format(date) + "\t\t");
        });
        t.start();
    }

    /**
     * loads Pie Chart.
     */
    private void loadPieChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Samsung", new Double(27.8));
        dataset.setValue("Others", new Double(55.3));
        dataset.setValue("Nokia", new Double(16.8));
        dataset.setValue("Apple", new Double(17.1));

        pnlPieChart.add(new PieChartCreator().createDemoPanel(dataset,
                "Pie Chart Title Goes Here"));
    }

    /**
     * loads Bar Chart.
     *
     * @return The dataset.
     */
    private void loadBarChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(7445, "JFreeSVG", "Warm-up");
        dataset.addValue(24448, "Batik", "Warm-up");
        dataset.addValue(4297, "JFreeSVG", "Test");
        dataset.addValue(21022, "Batik", "Test");
        pnlBarChart.add(new BarChartCreator().createDemoPanel(dataset,
                "Title"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlWelcome = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        lblDateAndTime = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        pnlDoctor = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cmbSearch = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ptxtAddress = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ptxtMobile = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ptxtContactName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ptxtContactMobile = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        txtNIC = new javax.swing.JTextField();
        cmbTitle = new javax.swing.JComboBox();
        txtFirstName = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        dtBirthDate = new com.toedter.calendar.JDateChooser();
        jPanel20 = new javax.swing.JPanel();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        txtPhoto = new javax.swing.JTextField();
        btnPhoto = new javax.swing.JButton();
        txtContactName = new javax.swing.JTextField();
        txtContactMobile = new javax.swing.JTextField();
        txtContactEmail = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        pnlUser = new javax.swing.JPanel();
        pnlSummary = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        pnlPieChart = new javax.swing.JPanel();
        pnlBarChart = new javax.swing.JPanel();
        pnlTemp = new javax.swing.JPanel();
        pnlTemp2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        SoftBorderPane = new javax.swing.JPanel();
        DocBarPane = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/banner-blood.jpg"))); // NOI18N
        lblBanner.setPreferredSize(new java.awt.Dimension(1000, 100));
        jPanel3.add(lblBanner);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(940, 450));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        pnlWelcome.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlWelcome.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/about.jpg"))); // NOI18N
        jPanel5.add(jLabel27, java.awt.BorderLayout.CENTER);

        jLabel28.setText("jLabel28");
        jPanel5.add(jLabel28, java.awt.BorderLayout.PAGE_START);
        jPanel5.add(jPanel23, java.awt.BorderLayout.PAGE_END);

        pnlWelcome.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Welcome");
        jPanel6.add(jLabel1);

        pnlWelcome.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jLabel29.setText("jLabel29");
        jPanel7.add(jLabel29);

        lblDateAndTime.setText(" Date And Time");
        jPanel7.add(lblDateAndTime);

        jProgressBar1.setIndeterminate(true);
        jPanel7.add(jProgressBar1);

        pnlWelcome.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Welcome </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/doctor.png")), pnlWelcome); // NOI18N

        pnlDoctor.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlDoctor.setLayout(new java.awt.GridLayout(1, 2));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><body bgcolor='#58FAF4'><center><b>Search for Doctor</b></center></body></html>", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel20.setText("Search Text");
        jPanel9.add(jLabel20);

        jPanel8.add(jPanel9);

        cmbSearch.setEditable(true);
        jPanel8.add(cmbSearch);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel21.setText("Doctors");
        jPanel10.add(jLabel21);

        jPanel8.add(jPanel10);

        tblSearch.setAutoCreateRowSorter(true);
        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rid", "Name", "Gender", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSearch);

        jPanel8.add(jScrollPane2);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel18.setText("Selected Doctor More Info");
        jPanel11.add(jLabel18);

        jPanel8.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel14.setLayout(new java.awt.BorderLayout());
        jPanel14.add(lblPhoto, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel14);

        jPanel13.setLayout(new java.awt.GridLayout(4, 2));

        jLabel19.setText("Address");
        jPanel13.add(jLabel19);

        ptxtAddress.setEditable(false);
        jPanel13.add(ptxtAddress);

        jLabel22.setText("Phone");
        jPanel13.add(jLabel22);

        ptxtMobile.setEditable(false);
        jPanel13.add(ptxtMobile);

        jLabel23.setText("Contact Person");
        jPanel13.add(jLabel23);

        ptxtContactName.setEditable(false);
        jPanel13.add(ptxtContactName);

        jLabel24.setText("Contacter Phone");
        jPanel13.add(jLabel24);

        ptxtContactMobile.setEditable(false);
        jPanel13.add(ptxtContactMobile);

        jPanel12.add(jPanel13);

        jPanel8.add(jPanel12);
        jPanel8.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jButton1.setText("Quit");
        jPanel16.add(jButton1);

        btnContinue.setText("Continue");
        jPanel16.add(btnContinue);

        jPanel8.add(jPanel16);

        pnlDoctor.add(jPanel8);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><body bgcolor='#58FAF4'><center><b> Creates a Doctor </b></center></body></html>", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP));
        jPanel17.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel18.setLayout(new java.awt.GridLayout(18, 1));

        jLabel2.setText("NIC");
        jPanel18.add(jLabel2);

        jLabel3.setText("Title");
        jPanel18.add(jLabel3);

        jLabel4.setText("First Name");
        jPanel18.add(jLabel4);

        jLabel5.setText("Middle Name");
        jPanel18.add(jLabel5);

        jLabel6.setText("Last Name");
        jPanel18.add(jLabel6);

        jLabel17.setText("Birth Date");
        jPanel18.add(jLabel17);

        jLabel7.setText("Gender");
        jPanel18.add(jLabel7);

        jLabel8.setText("Address 1");
        jPanel18.add(jLabel8);

        jLabel9.setText("Address 2");
        jPanel18.add(jLabel9);

        jLabel10.setText("City");
        jPanel18.add(jLabel10);

        jLabel11.setText("Phone");
        jPanel18.add(jLabel11);

        jLabel12.setText("Email");
        jPanel18.add(jLabel12);

        jLabel13.setText("Photo");
        jPanel18.add(jLabel13);

        jLabel14.setText("Contact Person Name");
        jPanel18.add(jLabel14);

        jLabel15.setText("Contact Person Mobile");
        jPanel18.add(jLabel15);

        jLabel25.setText("Contact Person Email");
        jPanel18.add(jLabel25);
        jPanel18.add(jLabel16);

        btnCancel.setText("Clear");
        jPanel18.add(btnCancel);

        jPanel17.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(18, 1));

        txtNIC.setText("901563350V");
        jPanel19.add(txtNIC);

        cmbTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr. ", "Mrs. ", "Miss. " }));
        jPanel19.add(cmbTitle);

        txtFirstName.setText("Saman");
        jPanel19.add(txtFirstName);

        txtMiddleName.setText("Nimal");
        jPanel19.add(txtMiddleName);

        txtLastName.setText("Sunil");
        jPanel19.add(txtLastName);

        dtBirthDate.setDateFormatString("yyyy-MM-dd");
        jPanel19.add(dtBirthDate);

        jPanel20.setLayout(new java.awt.GridLayout(1, 2));

        radMale.setSelected(true);
        radMale.setText("  Male");
        jPanel20.add(radMale);

        radFemale.setText("  Female");
        jPanel20.add(radFemale);

        jPanel19.add(jPanel20);

        txtAddress1.setText("Somewhere");
        jPanel19.add(txtAddress1);

        txtAddress2.setText("Anywhere");
        jPanel19.add(txtAddress2);

        txtCity.setText("Galle");
        jPanel19.add(txtCity);

        txtMobile.setText("0710111000");
        jPanel19.add(txtMobile);

        txtEmail.setText("thmamaraseara@virtusa.com");
        jPanel19.add(txtEmail);

        jPanel21.setLayout(new java.awt.GridLayout(1, 2, 3, 0));

        txtPhoto.setEditable(false);
        jPanel21.add(txtPhoto);

        btnPhoto.setText("..");
        btnPhoto.setMaximumSize(new java.awt.Dimension(20, 15));
        btnPhoto.setMinimumSize(new java.awt.Dimension(20, 15));
        btnPhoto.setPreferredSize(new java.awt.Dimension(20, 15));
        jPanel21.add(btnPhoto);

        jPanel19.add(jPanel21);

        txtContactName.setText("Hansa");
        jPanel19.add(txtContactName);

        txtContactMobile.setText("0712004212");
        jPanel19.add(txtContactMobile);

        txtContactEmail.setText("hansa0712004212@gmail.com");
        jPanel19.add(txtContactEmail);
        jPanel19.add(jLabel26);

        btnSubmit.setText("Submit");
        jPanel19.add(btnSubmit);

        jPanel17.add(jPanel19);

        pnlDoctor.add(jPanel17);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Doctors </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/doctor.png")), pnlDoctor); // NOI18N

        pnlUser.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlUser.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Users </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/doctor.png")), pnlUser); // NOI18N

        pnlSummary.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlSummary.setLayout(new javax.swing.BoxLayout(pnlSummary, javax.swing.BoxLayout.LINE_AXIS));

        jPanel22.setLayout(new java.awt.GridLayout(1, 2));

        pnlPieChart.setLayout(new javax.swing.BoxLayout(pnlPieChart, javax.swing.BoxLayout.LINE_AXIS));
        jPanel22.add(pnlPieChart);
        jPanel22.add(pnlBarChart);

        pnlSummary.add(jPanel22);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Summary </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/doctor.png")), pnlSummary); // NOI18N

        pnlTemp.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlTemp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Label Here </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/doctor.png")), pnlTemp); // NOI18N

        pnlTemp2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlTemp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Label Here </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/doctor.png")), pnlTemp2); // NOI18N

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        SoftBorderPane.setPreferredSize(new java.awt.Dimension(900, 70));
        SoftBorderPane.setLayout(new javax.swing.BoxLayout(SoftBorderPane, javax.swing.BoxLayout.LINE_AXIS));
        SoftBorderPane.add(DocBarPane);

        jPanel4.add(SoftBorderPane);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        switch (jTabbedPane1.getSelectedIndex()) {
            case 0:

                break;
            case 1:

                break;
            case 2:

                break;
            case 3:
                loadPieChart();
                loadBarChart();
                break;
            default:
                Message.showErrorMessage("Invalid");
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMain(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DocBarPane;
    private javax.swing.JPanel SoftBorderPane;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cmbSearch;
    private javax.swing.JComboBox cmbTitle;
    private com.toedter.calendar.JDateChooser dtBirthDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblDateAndTime;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JPanel pnlBarChart;
    private javax.swing.JPanel pnlDoctor;
    private javax.swing.JPanel pnlPieChart;
    private javax.swing.JPanel pnlSummary;
    private javax.swing.JPanel pnlTemp;
    private javax.swing.JPanel pnlTemp2;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JTextField ptxtAddress;
    private javax.swing.JTextField ptxtContactMobile;
    private javax.swing.JTextField ptxtContactName;
    private javax.swing.JTextField ptxtMobile;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactEmail;
    private javax.swing.JTextField txtContactMobile;
    private javax.swing.JTextField txtContactName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtPhoto;
    // End of variables declaration//GEN-END:variables
}
