/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uom.research.thalassemia.ui;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.Timer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import uom.research.thalassemia.object.User;
import uom.research.thalassemia.util.BarChartCreator;
import uom.research.thalassemia.util.FillData;
import uom.research.thalassemia.util.LineChartCreator;
import uom.research.thalassemia.util.Message;
import uom.research.thalassemia.util.ObjectDockLoader;
import uom.research.thalassemia.util.PieChartCreator;
import uom.research.thalassemia.util.StretchImage;

/**
 *
 * @author hansa
 */
public class HomeMain extends javax.swing.JFrame {

    /**
     * simple date time formatter. yyyy-MM-dd HH:mm:ss
     */
    private static final SimpleDateFormat DATE_TIME_FORMAT
            = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    /**
     * DateTime keeper.
     */
    private Date date;

    /**
     * One Second In MiliSeconds.
     */
    private static final int ONE_S_IN_MS = 1000;

    /**
     * logged in user.
     */
    private final User user;

    /**
     * Creates new form HomeMain.
     *
     * @param pUser user
     */
    public HomeMain(final User pUser) {
        initComponents();
        user = pUser;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        lblBanner.setSize(this.getWidth(), 50);
        ObjectDockLoader objectDockLoader = new ObjectDockLoader(DocBarPane,
                HomeMain.this);
        objectDockLoader.toString();
        FillData.setIconForJFrame(HomeMain.this);
        StretchImage.setImageStretch(lblBanner,
                new ImageIcon(getClass().getResource(
                        "/uom/research/thalassemia/images/banner-blood.jpg")));
        StretchImage.setImageStretch(lblThal2,
                new ImageIcon(getClass().getResource(
                        "/uom/research/thalassemia/images/thal2.jpg")));
        setClock();
    }

    /**
     * run clock.
     */
    private void setClock() {
        Timer t = new Timer(ONE_S_IN_MS, (ActionEvent evt) -> {
            date = new Date();
            lblDateAndTime.setText("\t\t" + DATE_TIME_FORMAT.format(date) + "\t\t");
        });
        t.start();
    }

    /**
     * loads Pie Chart.
     */
    private void loadPieChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue("Samsung", new Double(27.8));
        dataset.setValue("Others", new Double(55.3));
        dataset.setValue("Nokia", new Double(16.8));
        dataset.setValue("Apple", new Double(17.1));
        pnlPieChart.removeAll();
        pnlPieChart.add(new PieChartCreator().createPanel(dataset,
                "Pie Chart Title Goes Here"));
    }

    /**
     * loads Bar Chart.
     *
     * @return The dataset.
     */
    private void loadBarChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(7445, "JFreeSVG", "Warm-up");
        dataset.addValue(24448, "Batik", "Warm-up");
        dataset.addValue(4297, "JFreeSVG", "Test");
        dataset.addValue(21022, "Batik", "Test");
        pnlBarChart.removeAll();
        pnlBarChart.add(new BarChartCreator().createPanel(dataset,
                "Title", "SubTitle", "xTitle", "yTitle"));
    }

    /**
     * loads Line Chart.
     *
     * @return The dataset.
     */
    private void loadLineChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(15, "schools", "1970");
        dataset.addValue(30, "schools", "1980");
        dataset.addValue(60, "schools", "1990");
        dataset.addValue(120, "schools", "2000");
        dataset.addValue(240, "schools", "2010");
        dataset.addValue(300, "schools", "2014");
        pnlLineChart.removeAll();
        pnlLineChart.add(new LineChartCreator().createPanel(dataset,
                "Title", "subtitle", "x axis", "y axis"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        SoftBorderPane = new javax.swing.JPanel();
        DocBarPane = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlWelcome = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblThal2 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        lblDateAndTime = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        pnlDoctor = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cmbSearch = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ptxtAddress = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ptxtMobile = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ptxtContactName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ptxtContactMobile = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        txtNIC = new javax.swing.JTextField();
        cmbTitle = new javax.swing.JComboBox();
        txtFirstName = new javax.swing.JTextField();
        txtMiddleName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        dtBirthDate = new com.toedter.calendar.JDateChooser();
        jPanel20 = new javax.swing.JPanel();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        txtAddress1 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        txtPhoto = new javax.swing.JTextField();
        btnPhoto = new javax.swing.JButton();
        txtContactName = new javax.swing.JTextField();
        txtContactMobile = new javax.swing.JTextField();
        txtContactEmail = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        pnlUser = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        cmbUserSearch = new javax.swing.JComboBox();
        jPanel26 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUserSearch = new javax.swing.JTable();
        jPanel27 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        lblUserPhoto = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        ptxtUserAddress = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        ptxtUserMobile = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        ptxtUserContactName = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        ptxtUserContactMobile = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnUserContinue = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        btnUserCancel = new javax.swing.JButton();
        jPanel35 = new javax.swing.JPanel();
        txtUserNIC = new javax.swing.JTextField();
        cmbUserTitle = new javax.swing.JComboBox();
        txtUserFirstName = new javax.swing.JTextField();
        txtUserMiddleName = new javax.swing.JTextField();
        txtUserLastName = new javax.swing.JTextField();
        dtUserBirthDate = new com.toedter.calendar.JDateChooser();
        jPanel36 = new javax.swing.JPanel();
        radUserMale = new javax.swing.JRadioButton();
        radUserFemale = new javax.swing.JRadioButton();
        txtUserAddress1 = new javax.swing.JTextField();
        txtUserAddress2 = new javax.swing.JTextField();
        txtUserCity = new javax.swing.JTextField();
        txtUserMobile = new javax.swing.JTextField();
        txtUserEmail = new javax.swing.JTextField();
        jPanel37 = new javax.swing.JPanel();
        txtUserPhoto = new javax.swing.JTextField();
        btnUserPhoto = new javax.swing.JButton();
        txtUserContactName = new javax.swing.JTextField();
        txtUserContactMobile = new javax.swing.JTextField();
        txtUserContactEmail = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        btnUserSubmit = new javax.swing.JButton();
        pnlPatient = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        cmbPatientSearch = new javax.swing.JComboBox();
        jPanel45 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPatientSearch = new javax.swing.JTable();
        jPanel46 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        btnPatientCancel = new javax.swing.JButton();
        jPanel40 = new javax.swing.JPanel();
        txtPatientNIC = new javax.swing.JTextField();
        cmbPatientTitle = new javax.swing.JComboBox();
        txtPatientFirstName = new javax.swing.JTextField();
        txtPatientMiddleName = new javax.swing.JTextField();
        txtPatientLastName = new javax.swing.JTextField();
        dtPatientBirthDate = new com.toedter.calendar.JDateChooser();
        jPanel41 = new javax.swing.JPanel();
        radPatientMale = new javax.swing.JRadioButton();
        radPatientFemale = new javax.swing.JRadioButton();
        txtPatientAddress1 = new javax.swing.JTextField();
        txtPatientAddress2 = new javax.swing.JTextField();
        txtPatientCity = new javax.swing.JTextField();
        txtPatientMobile = new javax.swing.JTextField();
        txtPatientEmail = new javax.swing.JTextField();
        jPanel42 = new javax.swing.JPanel();
        txtPatientPhoto = new javax.swing.JTextField();
        btnPatientPhoto = new javax.swing.JButton();
        txtPatientContactName = new javax.swing.JTextField();
        txtPatientContactMobile = new javax.swing.JTextField();
        txtPatientContactEmail = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        btnPatientSubmit = new javax.swing.JButton();
        pnlSummary = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        pnlPieChart = new javax.swing.JPanel();
        pnlBarChart = new javax.swing.JPanel();
        pnlTemp2 = new javax.swing.JPanel();
        pnlLineChart = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLogOut = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thalassemia Identification System");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        SoftBorderPane.setPreferredSize(new java.awt.Dimension(900, 70));
        SoftBorderPane.setLayout(new javax.swing.BoxLayout(SoftBorderPane, javax.swing.BoxLayout.LINE_AXIS));
        SoftBorderPane.add(DocBarPane);

        jPanel4.add(SoftBorderPane);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/banner-blood.jpg"))); // NOI18N
        jPanel3.add(lblBanner, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(940, 450));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        pnlWelcome.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlWelcome.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("By Eyeanemia");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 973, -1));
        jPanel5.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 973, -1));

        jLabel76.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(204, 18, 18));
        jLabel76.setText("What is Thalassemia ?");
        jPanel5.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, -1));

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel27.setText("<html> <p align=\"justify\"> Thalassemia is a blood disorder passed down through families (inherited) in which the body makes an abnormal form of hemoglobin, the protein in red blood cells that carries oxygen.The disorder results in excessive destruction of red blood cells, which leads to anemia.Anemia is a disorder in which your body doesn’t have enough normal, healthy red blood cells (RBC). </p> </html>");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, 80));
        jPanel5.add(lblThal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 280, 180));
        jPanel5.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        pnlWelcome.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Thalassemia Identifier");
        jPanel6.add(jLabel1);

        pnlWelcome.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jLabel29.setText("Welcome                 ");
        jPanel7.add(jLabel29);

        lblDateAndTime.setText(" Date And Time");
        jPanel7.add(lblDateAndTime);

        jProgressBar1.setIndeterminate(true);
        jPanel7.add(jProgressBar1);

        pnlWelcome.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Welcome </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/welcome.png")), pnlWelcome); // NOI18N

        pnlDoctor.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlDoctor.setLayout(new java.awt.GridLayout(1, 2));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><body bgcolor='#58FAF4'><center><b>Search for Doctor</b></center></body></html>", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel20.setText("Search Text");
        jPanel9.add(jLabel20);

        jPanel8.add(jPanel9);

        cmbSearch.setEditable(true);
        jPanel8.add(cmbSearch);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel21.setText("Doctors");
        jPanel10.add(jLabel21);

        jPanel8.add(jPanel10);

        tblSearch.setAutoCreateRowSorter(true);
        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rid", "Name", "Gender", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSearch);

        jPanel8.add(jScrollPane2);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel18.setText("Selected Doctor More Info");
        jPanel11.add(jLabel18);

        jPanel8.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel14.setLayout(new java.awt.BorderLayout());
        jPanel14.add(lblPhoto, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel14);

        jPanel13.setLayout(new java.awt.GridLayout(4, 2));

        jLabel19.setText("Address");
        jPanel13.add(jLabel19);

        ptxtAddress.setEditable(false);
        jPanel13.add(ptxtAddress);

        jLabel22.setText("Phone");
        jPanel13.add(jLabel22);

        ptxtMobile.setEditable(false);
        jPanel13.add(ptxtMobile);

        jLabel23.setText("Contact Person");
        jPanel13.add(jLabel23);

        ptxtContactName.setEditable(false);
        jPanel13.add(ptxtContactName);

        jLabel24.setText("Contacter Phone");
        jPanel13.add(jLabel24);

        ptxtContactMobile.setEditable(false);
        jPanel13.add(ptxtContactMobile);

        jPanel12.add(jPanel13);

        jPanel8.add(jPanel12);
        jPanel8.add(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jButton1.setText("Quit");
        jPanel16.add(jButton1);

        btnContinue.setText("Continue");
        jPanel16.add(btnContinue);

        jPanel8.add(jPanel16);

        pnlDoctor.add(jPanel8);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><body bgcolor='#58FAF4'><center><b> Creates a Doctor </b></center></body></html>", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP));
        jPanel17.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel18.setLayout(new java.awt.GridLayout(18, 1));

        jLabel2.setText("NIC");
        jPanel18.add(jLabel2);

        jLabel3.setText("Title");
        jPanel18.add(jLabel3);

        jLabel4.setText("First Name");
        jPanel18.add(jLabel4);

        jLabel5.setText("Middle Name");
        jPanel18.add(jLabel5);

        jLabel6.setText("Last Name");
        jPanel18.add(jLabel6);

        jLabel17.setText("Birth Date");
        jPanel18.add(jLabel17);

        jLabel7.setText("Gender");
        jPanel18.add(jLabel7);

        jLabel8.setText("Address 1");
        jPanel18.add(jLabel8);

        jLabel9.setText("Address 2");
        jPanel18.add(jLabel9);

        jLabel10.setText("City");
        jPanel18.add(jLabel10);

        jLabel11.setText("Phone");
        jPanel18.add(jLabel11);

        jLabel12.setText("Email");
        jPanel18.add(jLabel12);

        jLabel13.setText("Photo");
        jPanel18.add(jLabel13);

        jLabel14.setText("Contact Person Name");
        jPanel18.add(jLabel14);

        jLabel15.setText("Contact Person Mobile");
        jPanel18.add(jLabel15);

        jLabel25.setText("Contact Person Email");
        jPanel18.add(jLabel25);
        jPanel18.add(jLabel16);

        btnCancel.setText("Clear");
        jPanel18.add(btnCancel);

        jPanel17.add(jPanel18);

        jPanel19.setLayout(new java.awt.GridLayout(18, 1));

        txtNIC.setText("901563350V");
        jPanel19.add(txtNIC);

        cmbTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr. ", "Mrs. ", "Miss. " }));
        jPanel19.add(cmbTitle);

        txtFirstName.setText("Saman");
        jPanel19.add(txtFirstName);

        txtMiddleName.setText("Nimal");
        jPanel19.add(txtMiddleName);

        txtLastName.setText("Sunil");
        jPanel19.add(txtLastName);

        dtBirthDate.setDateFormatString("yyyy-MM-dd");
        jPanel19.add(dtBirthDate);

        jPanel20.setLayout(new java.awt.GridLayout(1, 2));

        radMale.setSelected(true);
        radMale.setText("  Male");
        jPanel20.add(radMale);

        radFemale.setText("  Female");
        jPanel20.add(radFemale);

        jPanel19.add(jPanel20);

        txtAddress1.setText("Somewhere");
        jPanel19.add(txtAddress1);

        txtAddress2.setText("Anywhere");
        jPanel19.add(txtAddress2);

        txtCity.setText("Galle");
        jPanel19.add(txtCity);

        txtMobile.setText("0710111000");
        jPanel19.add(txtMobile);

        txtEmail.setText("thmamaraseara@virtusa.com");
        jPanel19.add(txtEmail);

        jPanel21.setLayout(new java.awt.GridLayout(1, 2, 3, 0));

        txtPhoto.setEditable(false);
        jPanel21.add(txtPhoto);

        btnPhoto.setText("..");
        btnPhoto.setMaximumSize(new java.awt.Dimension(20, 15));
        btnPhoto.setMinimumSize(new java.awt.Dimension(20, 15));
        btnPhoto.setPreferredSize(new java.awt.Dimension(20, 15));
        jPanel21.add(btnPhoto);

        jPanel19.add(jPanel21);

        txtContactName.setText("Hansa");
        jPanel19.add(txtContactName);

        txtContactMobile.setText("0712004212");
        jPanel19.add(txtContactMobile);

        txtContactEmail.setText("hansa0712004212@gmail.com");
        jPanel19.add(txtContactEmail);
        jPanel19.add(jLabel26);

        btnSubmit.setText("Submit");
        jPanel19.add(btnSubmit);

        jPanel17.add(jPanel19);

        pnlDoctor.add(jPanel17);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Doctors </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/doctor.png")), pnlDoctor); // NOI18N

        pnlUser.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlUser.setLayout(new java.awt.GridLayout(1, 2));

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><body bgcolor='#58FAF4'><center><b>Search for User</b></center></body></html>", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel30.setText("Search Text");
        jPanel25.add(jLabel30);

        jPanel24.add(jPanel25);

        cmbUserSearch.setEditable(true);
        jPanel24.add(cmbUserSearch);

        jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel31.setText("Users");
        jPanel26.add(jLabel31);

        jPanel24.add(jPanel26);

        tblUserSearch.setAutoCreateRowSorter(true);
        tblUserSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rid", "Name", "Gender", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblUserSearch);

        jPanel24.add(jScrollPane3);

        jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel32.setText("Selected User More Info");
        jPanel27.add(jLabel32);

        jPanel24.add(jPanel27);

        jPanel28.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel29.setLayout(new java.awt.BorderLayout());
        jPanel29.add(lblUserPhoto, java.awt.BorderLayout.CENTER);

        jPanel28.add(jPanel29);

        jPanel30.setLayout(new java.awt.GridLayout(4, 2));

        jLabel33.setText("Address");
        jPanel30.add(jLabel33);

        ptxtUserAddress.setEditable(false);
        jPanel30.add(ptxtUserAddress);

        jLabel34.setText("Phone");
        jPanel30.add(jLabel34);

        ptxtUserMobile.setEditable(false);
        jPanel30.add(ptxtUserMobile);

        jLabel35.setText("Contact Person");
        jPanel30.add(jLabel35);

        ptxtUserContactName.setEditable(false);
        jPanel30.add(ptxtUserContactName);

        jLabel36.setText("Contacter Phone");
        jPanel30.add(jLabel36);

        ptxtUserContactMobile.setEditable(false);
        jPanel30.add(ptxtUserContactMobile);

        jPanel28.add(jPanel30);

        jPanel24.add(jPanel28);
        jPanel24.add(jPanel31);

        jPanel32.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jButton2.setText("Quit");
        jPanel32.add(jButton2);

        btnUserContinue.setText("Continue");
        jPanel32.add(btnUserContinue);

        jPanel24.add(jPanel32);

        pnlUser.add(jPanel24);

        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><body bgcolor='#58FAF4'><center><b> Creates a User </b></center></body></html>", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP));
        jPanel33.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel34.setLayout(new java.awt.GridLayout(18, 1));

        jLabel37.setText("NIC");
        jPanel34.add(jLabel37);

        jLabel38.setText("Title");
        jPanel34.add(jLabel38);

        jLabel39.setText("First Name");
        jPanel34.add(jLabel39);

        jLabel40.setText("Middle Name");
        jPanel34.add(jLabel40);

        jLabel41.setText("Last Name");
        jPanel34.add(jLabel41);

        jLabel42.setText("Birth Date");
        jPanel34.add(jLabel42);

        jLabel43.setText("Gender");
        jPanel34.add(jLabel43);

        jLabel44.setText("Address 1");
        jPanel34.add(jLabel44);

        jLabel45.setText("Address 2");
        jPanel34.add(jLabel45);

        jLabel46.setText("City");
        jPanel34.add(jLabel46);

        jLabel47.setText("Phone");
        jPanel34.add(jLabel47);

        jLabel48.setText("Email");
        jPanel34.add(jLabel48);

        jLabel49.setText("Photo");
        jPanel34.add(jLabel49);

        jLabel50.setText("Contact Person Name");
        jPanel34.add(jLabel50);

        jLabel51.setText("Contact Person Mobile");
        jPanel34.add(jLabel51);

        jLabel52.setText("Contact Person Email");
        jPanel34.add(jLabel52);
        jPanel34.add(jLabel53);

        btnUserCancel.setText("Clear");
        jPanel34.add(btnUserCancel);

        jPanel33.add(jPanel34);

        jPanel35.setLayout(new java.awt.GridLayout(18, 1));

        txtUserNIC.setText("901563350V");
        jPanel35.add(txtUserNIC);

        cmbUserTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr. ", "Mrs. ", "Miss. " }));
        jPanel35.add(cmbUserTitle);

        txtUserFirstName.setText("Saman");
        jPanel35.add(txtUserFirstName);

        txtUserMiddleName.setText("Nimal");
        jPanel35.add(txtUserMiddleName);

        txtUserLastName.setText("Sunil");
        jPanel35.add(txtUserLastName);

        dtUserBirthDate.setDateFormatString("yyyy-MM-dd");
        jPanel35.add(dtUserBirthDate);

        jPanel36.setLayout(new java.awt.GridLayout(1, 2));

        radUserMale.setSelected(true);
        radUserMale.setText("  Male");
        jPanel36.add(radUserMale);

        radUserFemale.setText("  Female");
        jPanel36.add(radUserFemale);

        jPanel35.add(jPanel36);

        txtUserAddress1.setText("Somewhere");
        jPanel35.add(txtUserAddress1);

        txtUserAddress2.setText("Anywhere");
        jPanel35.add(txtUserAddress2);

        txtUserCity.setText("Galle");
        jPanel35.add(txtUserCity);

        txtUserMobile.setText("0710111000");
        jPanel35.add(txtUserMobile);

        txtUserEmail.setText("thmamaraseara@virtusa.com");
        jPanel35.add(txtUserEmail);

        jPanel37.setLayout(new java.awt.GridLayout(1, 2, 3, 0));

        txtUserPhoto.setEditable(false);
        jPanel37.add(txtUserPhoto);

        btnUserPhoto.setText("..");
        btnUserPhoto.setMaximumSize(new java.awt.Dimension(20, 15));
        btnUserPhoto.setMinimumSize(new java.awt.Dimension(20, 15));
        btnUserPhoto.setPreferredSize(new java.awt.Dimension(20, 15));
        jPanel37.add(btnUserPhoto);

        jPanel35.add(jPanel37);

        txtUserContactName.setText("Hansa");
        jPanel35.add(txtUserContactName);

        txtUserContactMobile.setText("0712004212");
        jPanel35.add(txtUserContactMobile);

        txtUserContactEmail.setText("hansa0712004212@gmail.com");
        jPanel35.add(txtUserContactEmail);
        jPanel35.add(jLabel54);

        btnUserSubmit.setText("Submit");
        jPanel35.add(btnUserSubmit);

        jPanel33.add(jPanel35);

        pnlUser.add(jPanel33);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Users </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/user.png")), pnlUser); // NOI18N

        pnlPatient.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlPatient.setLayout(new java.awt.GridLayout(1, 2));

        jPanel43.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><body bgcolor='#58FAF4'><center><b>Search for Patient</b></center></body></html>", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel43.setLayout(new javax.swing.BoxLayout(jPanel43, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel44.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel73.setText("Search Text");
        jPanel44.add(jLabel73);

        jPanel43.add(jPanel44);

        cmbPatientSearch.setEditable(true);
        jPanel43.add(cmbPatientSearch);

        jPanel45.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel74.setText("Patients");
        jPanel45.add(jLabel74);

        jPanel43.add(jPanel45);

        tblPatientSearch.setAutoCreateRowSorter(true);
        tblPatientSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rid", "Name", "Gender", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblPatientSearch);

        jPanel43.add(jScrollPane4);

        jPanel46.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel75.setText("Selected Patient More Info");
        jPanel46.add(jLabel75);

        jPanel43.add(jPanel46);

        jPanel47.setLayout(new java.awt.GridLayout(3, 2, 0, 2));

        jButton4.setText("Update Patient ...");
        jPanel47.add(jButton4);

        jButton5.setText("Delete Patient");
        jPanel47.add(jButton5);

        jButton6.setText("Upload Blood Images ...");
        jPanel47.add(jButton6);

        jButton7.setText("Perform Blood Cell Analysis ...");
        jPanel47.add(jButton7);

        jButton8.setText("jButton8");
        jPanel47.add(jButton8);

        jButton9.setText("jButton9");
        jPanel47.add(jButton9);

        jPanel43.add(jPanel47);

        pnlPatient.add(jPanel43);

        jPanel38.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<html><body bgcolor='#58FAF4'><center><b> Creates a Patient </b></center></body></html>", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP));
        jPanel38.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jPanel39.setLayout(new java.awt.GridLayout(18, 1));

        jLabel55.setText("NIC");
        jPanel39.add(jLabel55);

        jLabel56.setText("Title");
        jPanel39.add(jLabel56);

        jLabel57.setText("First Name");
        jPanel39.add(jLabel57);

        jLabel58.setText("Middle Name");
        jPanel39.add(jLabel58);

        jLabel59.setText("Last Name");
        jPanel39.add(jLabel59);

        jLabel60.setText("Birth Date");
        jPanel39.add(jLabel60);

        jLabel61.setText("Gender");
        jPanel39.add(jLabel61);

        jLabel62.setText("Address 1");
        jPanel39.add(jLabel62);

        jLabel63.setText("Address 2");
        jPanel39.add(jLabel63);

        jLabel64.setText("City");
        jPanel39.add(jLabel64);

        jLabel65.setText("Phone");
        jPanel39.add(jLabel65);

        jLabel66.setText("Email");
        jPanel39.add(jLabel66);

        jLabel67.setText("Photo");
        jPanel39.add(jLabel67);

        jLabel68.setText("Contact Person Name");
        jPanel39.add(jLabel68);

        jLabel69.setText("Contact Person Mobile");
        jPanel39.add(jLabel69);

        jLabel70.setText("Contact Person Email");
        jPanel39.add(jLabel70);
        jPanel39.add(jLabel71);

        btnPatientCancel.setText("Clear");
        jPanel39.add(btnPatientCancel);

        jPanel38.add(jPanel39);

        jPanel40.setLayout(new java.awt.GridLayout(18, 1));

        txtPatientNIC.setText("901563350V");
        jPanel40.add(txtPatientNIC);

        cmbPatientTitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mr. ", "Mrs. ", "Miss. " }));
        jPanel40.add(cmbPatientTitle);

        txtPatientFirstName.setText("Saman");
        jPanel40.add(txtPatientFirstName);

        txtPatientMiddleName.setText("Nimal");
        jPanel40.add(txtPatientMiddleName);

        txtPatientLastName.setText("Sunil");
        jPanel40.add(txtPatientLastName);

        dtPatientBirthDate.setDateFormatString("yyyy-MM-dd");
        jPanel40.add(dtPatientBirthDate);

        jPanel41.setLayout(new java.awt.GridLayout(1, 2));

        radPatientMale.setSelected(true);
        radPatientMale.setText("  Male");
        jPanel41.add(radPatientMale);

        radPatientFemale.setText("  Female");
        jPanel41.add(radPatientFemale);

        jPanel40.add(jPanel41);

        txtPatientAddress1.setText("Somewhere");
        jPanel40.add(txtPatientAddress1);

        txtPatientAddress2.setText("Anywhere");
        jPanel40.add(txtPatientAddress2);

        txtPatientCity.setText("Galle");
        jPanel40.add(txtPatientCity);

        txtPatientMobile.setText("0710111000");
        jPanel40.add(txtPatientMobile);

        txtPatientEmail.setText("thmamaraseara@virtusa.com");
        jPanel40.add(txtPatientEmail);

        jPanel42.setLayout(new java.awt.GridLayout(1, 2, 3, 0));

        txtPatientPhoto.setEditable(false);
        jPanel42.add(txtPatientPhoto);

        btnPatientPhoto.setText("..");
        btnPatientPhoto.setMaximumSize(new java.awt.Dimension(20, 15));
        btnPatientPhoto.setMinimumSize(new java.awt.Dimension(20, 15));
        btnPatientPhoto.setPreferredSize(new java.awt.Dimension(20, 15));
        jPanel42.add(btnPatientPhoto);

        jPanel40.add(jPanel42);

        txtPatientContactName.setText("Hansa");
        jPanel40.add(txtPatientContactName);

        txtPatientContactMobile.setText("0712004212");
        jPanel40.add(txtPatientContactMobile);

        txtPatientContactEmail.setText("hansa0712004212@gmail.com");
        jPanel40.add(txtPatientContactEmail);
        jPanel40.add(jLabel72);

        btnPatientSubmit.setText("Submit");
        jPanel40.add(btnPatientSubmit);

        jPanel38.add(jPanel40);

        pnlPatient.add(jPanel38);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Patients </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/patient.png")), pnlPatient); // NOI18N

        pnlSummary.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlSummary.setLayout(new javax.swing.BoxLayout(pnlSummary, javax.swing.BoxLayout.LINE_AXIS));

        jPanel22.setLayout(new java.awt.GridLayout(1, 2));

        pnlPieChart.setLayout(new java.awt.BorderLayout());
        jPanel22.add(pnlPieChart);

        pnlBarChart.setLayout(new java.awt.BorderLayout());
        jPanel22.add(pnlBarChart);

        pnlSummary.add(jPanel22);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Summary </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/summary.png")), pnlSummary); // NOI18N

        pnlTemp2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pnlTemp2.setLayout(new java.awt.GridLayout(1, 2));

        pnlLineChart.setLayout(new java.awt.BorderLayout());
        pnlTemp2.add(pnlLineChart);
        pnlTemp2.add(jPanel49);

        jTabbedPane1.addTab("<html><div style='text-align: center;'><br/><br/><br/> Label Here </div></html>", new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/doctor.png")), pnlTemp2); // NOI18N

        jPanel2.add(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jMenu1.setText("File");

        mnuLogOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/login.png"))); // NOI18N
        mnuLogOut.setText("  Log Out ...");
        mnuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLogOut);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uom/research/thalassemia/images/exit.png"))); // NOI18N
        mnuExit.setText("  Exit ...");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        switch (jTabbedPane1.getSelectedIndex()) {
            case 0:

                break;
            case 1:

                break;
            case 2:

                break;
            case 3:

                break;
            case 4:
                loadPieChart();
                loadBarChart();
                break;
            case 5:
                loadLineChart();
                break;
            default:
                Message.showErrorMessage("Invalid");
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void mnuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogOutActionPerformed
        if (Message.showQuestionYesNo(
                " Do You Really Need To Log Out ? ")
                == Message.YES_OPTION) {
            HomeMain.this.dispose();
            new Login(null, true).setVisible(true);
        }
    }//GEN-LAST:event_mnuLogOutActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        if (Message.showQuestionYesNo(
                " Do You Really Need To Exit ? ")
                == Message.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMain(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DocBarPane;
    private javax.swing.JPanel SoftBorderPane;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnPatientCancel;
    private javax.swing.JButton btnPatientPhoto;
    private javax.swing.JButton btnPatientSubmit;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUserCancel;
    private javax.swing.JButton btnUserContinue;
    private javax.swing.JButton btnUserPhoto;
    private javax.swing.JButton btnUserSubmit;
    private javax.swing.JComboBox cmbPatientSearch;
    private javax.swing.JComboBox cmbPatientTitle;
    private javax.swing.JComboBox cmbSearch;
    private javax.swing.JComboBox cmbTitle;
    private javax.swing.JComboBox cmbUserSearch;
    private javax.swing.JComboBox cmbUserTitle;
    private com.toedter.calendar.JDateChooser dtBirthDate;
    private com.toedter.calendar.JDateChooser dtPatientBirthDate;
    private com.toedter.calendar.JDateChooser dtUserBirthDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblDateAndTime;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblThal2;
    private javax.swing.JLabel lblUserPhoto;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuLogOut;
    private javax.swing.JPanel pnlBarChart;
    private javax.swing.JPanel pnlDoctor;
    private javax.swing.JPanel pnlLineChart;
    private javax.swing.JPanel pnlPatient;
    private javax.swing.JPanel pnlPieChart;
    private javax.swing.JPanel pnlSummary;
    private javax.swing.JPanel pnlTemp2;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JTextField ptxtAddress;
    private javax.swing.JTextField ptxtContactMobile;
    private javax.swing.JTextField ptxtContactName;
    private javax.swing.JTextField ptxtMobile;
    private javax.swing.JTextField ptxtUserAddress;
    private javax.swing.JTextField ptxtUserContactMobile;
    private javax.swing.JTextField ptxtUserContactName;
    private javax.swing.JTextField ptxtUserMobile;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JRadioButton radPatientFemale;
    private javax.swing.JRadioButton radPatientMale;
    private javax.swing.JRadioButton radUserFemale;
    private javax.swing.JRadioButton radUserMale;
    private javax.swing.JTable tblPatientSearch;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTable tblUserSearch;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactEmail;
    private javax.swing.JTextField txtContactMobile;
    private javax.swing.JTextField txtContactName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtPatientAddress1;
    private javax.swing.JTextField txtPatientAddress2;
    private javax.swing.JTextField txtPatientCity;
    private javax.swing.JTextField txtPatientContactEmail;
    private javax.swing.JTextField txtPatientContactMobile;
    private javax.swing.JTextField txtPatientContactName;
    private javax.swing.JTextField txtPatientEmail;
    private javax.swing.JTextField txtPatientFirstName;
    private javax.swing.JTextField txtPatientLastName;
    private javax.swing.JTextField txtPatientMiddleName;
    private javax.swing.JTextField txtPatientMobile;
    private javax.swing.JTextField txtPatientNIC;
    private javax.swing.JTextField txtPatientPhoto;
    private javax.swing.JTextField txtPhoto;
    private javax.swing.JTextField txtUserAddress1;
    private javax.swing.JTextField txtUserAddress2;
    private javax.swing.JTextField txtUserCity;
    private javax.swing.JTextField txtUserContactEmail;
    private javax.swing.JTextField txtUserContactMobile;
    private javax.swing.JTextField txtUserContactName;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserFirstName;
    private javax.swing.JTextField txtUserLastName;
    private javax.swing.JTextField txtUserMiddleName;
    private javax.swing.JTextField txtUserMobile;
    private javax.swing.JTextField txtUserNIC;
    private javax.swing.JTextField txtUserPhoto;
    // End of variables declaration//GEN-END:variables
}
