package uom.research.thalassemia.ui;

/**
 * This class is use to display a progress bar when thread is busy.
 *
 * @author anupama
 */
public final class Progress extends javax.swing.JDialog {

    /**
     * Window width.
     */
    private static final int FRAME_WIDTH = 400;

    /**
     * Window height.
     */
    private static final int FRAME_HEIGHT = 62;

    /**
     * Creates new form Progress.
     *
     * @param parent parent form
     * @param modal is modal or not
     */
    public Progress(final java.awt.Frame parent, final boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(FRAME_WIDTH, FRAME_HEIGHT);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Please Wait ...");
        setAlwaysOnTop(true);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setString("Please Wait ...");
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
